all:
	$(MAKE) -C aclExample
	$(MAKE) -C appExample
	$(MAKE) -C fullExample
	$(MAKE) -C otpExample
	$(MAKE) -C secureStorageExample


clean:
	$(MAKE) -C aclExample clean
	$(MAKE) -C appExample clean
	$(MAKE) -C fullExample clean
	$(MAKE) -C otpExample clean
	$(MAKE) -C secureStorageExample clean

.PHONY: all clean
